services:
  auth_service:
    build: .
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - AUTH_ENV=${AUTH_ENV}
      - MONGO_URI_AUTH=${MONGO_URI_AUTH}
      - FLASK_AUTH_PORT=${FLASK_AUTH_PORT}
    volumes:
      - ./logs:/auth_microservice/logs
    networks:
      - omnis_network

networks:
  omnis_network:
    external: true
    name: omnis_network
