from flask import Blueprint, jsonify, request
from ..views import flow_cytometry_views as fcv
from app.views import gating_views as gv
from flask_jwt_extended import jwt_required, get_jwt_identity

bp = Blueprint('flow_cytometry', __name__)

# Route per caricare un nuovo esperimento di citofluorimetria
@bp.route('/api/v1/project/<project_id>/flow_cytometry', methods=['POST'])
@jwt_required()
def upload_fcs_file(project_id):
    user = get_jwt_identity()
    # Ottieni i dati dal request
    cytofluorimetry_file = request.files.get('cytofluorimetry_file')
    description = request.form.get('description', '')

    # Passa i dati alla view
    result, status_code = fcv.upload_flow_cytometry_file_views(project_id, cytofluorimetry_file, description, user)
    return jsonify(result), status_code

# route per fare l'upload in batch dei file di citofluorimetria
@bp.route('/api/v1/project/<project_id>/flow_cytometry/batch', methods=['POST'])
@jwt_required()
def upload_fcs_files(project_id):
    user = get_jwt_identity()
    print(request.files)
    # Ottieni i dati dal request
    cytofluorimetry_files = request.files.getlist('cytofluorimetry_files')
    workspace_files = request.files.getlist('wsp_files')
    metadata_file = request.files.get('metadata_file')

    # Passa i dati alla view
    result, status_code = fcv.upload_flow_cytometry_batch_files_views(project_id, cytofluorimetry_files, workspace_files, user, metadata_file)
    return jsonify(result), status_code


# Route per leggere un esperimento di citofluorimetria tramite ID
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>', methods=['GET'])
@jwt_required()
def get_fcs_file(project_id, progressive_id):
    user = get_jwt_identity()
    result, status_code = fcv.get_flow_cytometry_file_views(progressive_id, user)
    return result, status_code

# Route per leggere tutti gli esperimenti di citofluorimetria di un progetto specifico
@bp.route('/api/v1/project/<project_id>/flow_cytometry', methods=['GET'])
@jwt_required()
def get_fcs_files(project_id):
    user = get_jwt_identity()
    # fcs files
    result, status_code = fcv.get_flow_cytometry_files_views(project_id, user)
    return jsonify(result), status_code

# Route per aggiornare i metadati di un esperimento di citofluorimetria
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>', methods=['PUT'])
@jwt_required()
def update_fcs_file(project_id, progressive_id):
    user = get_jwt_identity()
    data = request.get_json()
    result, status_code = fcv.update_flow_cytometry_file_views(progressive_id, data, user)
    return jsonify(result), status_code

# Route per eliminare un esperimento di citofluorimetria
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>', methods=['DELETE'])
@jwt_required()
def delete_fcs_file(project_id, progressive_id):
    user = get_jwt_identity()
    result, status_code = fcv.delete_flow_cytometry_file_views(progressive_id, user)
    return jsonify(result), status_code


# crea la route per il salvataggio della pipeline
@bp.route('/api/v1/project/<project_id>/pipeline', methods=['POST'])
@jwt_required()
def save_pipeline_flow_cytometry(project_id):
    user = get_jwt_identity()
    data = request.get_json()
    pipe_data = data.get("body")
    result, status_code = fcv.save_flow_cytometry_pipeline_views(user, project_id, pipe_data)
    return jsonify(result), status_code


# crea la route per il processing della pipeline
@bp.route('/api/v1/project/<project_id>/process_pipeline', methods=['POST'])
@jwt_required()
def process_pipeline_flow_cytometry(project_id):
    user = get_jwt_identity()
    data = request.get_json()
    pipe_data = data.get("body")
    result, status_code = fcv.process_pipeline_flowCytometry_views(user, project_id, pipe_data)
    return jsonify(result), status_code



#route to get the flow cytometry running pipelines for a specific project
@bp.route('/api/v1/project/<project_id>/running_pipelines', methods=['GET'])
@jwt_required()
def get_running_pipelines(project_id):
    user = get_jwt_identity()
    result, status_code = fcv.get_fc_pipeline_run_by_project_id_views(project_id, user)
    return result, status_code

# route to get the data of the csv files generated by the pipeline
@bp.route('/api/v1/project/<project_id>/running_pipeline/<pipeline_id>', methods=['GET']) 
@jwt_required()
def get_pipeline_csv_data(project_id, pipeline_id):
    print("sono qui")
    user = get_jwt_identity()
    result, status_code = fcv.get_fc_pipeline_run_results(project_id, pipeline_id, user)
    return result, status_code


# function to retrieve heatmap data
@bp.route('/api/v1/project/<project_id>/heatmap/<pipeline_id>', methods=['GET']) 
@jwt_required()
def get_heatmap_csv_data(project_id, pipeline_id):
    user = get_jwt_identity()
    result, status_code = fcv.get_fc_pipeline_run_heatmap_results_views(project_id, pipeline_id, user)
    return result, status_code

# temporary route for gating data.. to be corrected when the implementation of the gating strategy is completed 
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>/gating_strategies/<gating_strategy_id>/scatterplot', methods=['GET'])
@jwt_required()
def get_flow_cytometry_gating_data(project_id, progressive_id, gating_strategy_id):
    username = get_jwt_identity()
    parent_id = request.args.get('parentId')
    if parent_id is None:
        result, status_code = gv.get_fcs_gating_view_by_progressive_id(username, project_id, progressive_id)
    else:
        result, status_code = gv.get_flow_cytometry_data_from_parent_id(username, project_id, progressive_id, gating_strategy_id, parent_id)
    return result, status_code


# GET REQUEST TO RETRIEVE ALL GATES FOR A SPECIFIC FLOW CYTOMETRY OBJECT
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>/gates', methods=['GET'])
@jwt_required()
def get_all_gates_for_flow_cytometry(project_id, progressive_id):
    user = get_jwt_identity()
    result, status_code = gv.get_all_gates_for_flow_cytometry(user, project_id, progressive_id)
    return result, status_code


# POST request to create a new gating strategy
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>/gating_strategies', methods=['POST'])
@jwt_required()
def create_gating_strategy(project_id, progressive_id):
    user = get_jwt_identity()
    data = request.get_json()
    result, status_code = gv.create_gating_strategy_views(user, project_id, progressive_id, data)
    return result, status_code


# GET request to retrieve all gating strategies for a specific flow cytometry object
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>/gating_strategies', methods=['GET'])
@jwt_required()
def get_all_gating_strategies(project_id, progressive_id):
    user = get_jwt_identity()
    result, status_code = gv.get_all_gating_strategies_for_flow_cytometry(user, project_id, progressive_id)
    return result, status_code

# GET request to retrieve a gating strategy by its progressive id
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>/gating_strategies/<gating_strategy_id>', methods=['GET'])
@jwt_required()
def get_gating_strategy_by_progressive_id(project_id, progressive_id, gating_strategy_id):
    user = get_jwt_identity()
    result, status_code = gv.get_gating_strategy_by_progressive_id(user, project_id, progressive_id, gating_strategy_id)
    return result, status_code

# DELETE request to delete a gating strategy
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<progressive_id>/gating_strategies/<gating_strategy_id>', methods=['DELETE'])
@jwt_required()
def delete_gating_strategy(project_id, progressive_id, gating_strategy_id):
    user = get_jwt_identity()
    result, status_code = gv.delete_gating_strategy(user, project_id, progressive_id, gating_strategy_id)
    return result, status_code

    
# route to retrieve all the gating elements for a specific gating strategy
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<flow_cytometry_id>/gating_strategies/<gating_strategy_id>/gating_elements', methods=['GET'])
@jwt_required()
def get_all_gating_elements_for_gating_strategy(project_id, flow_cytometry_id, gating_strategy_id):
    user = get_jwt_identity()
    result, status_code = gv.get_all_gating_elements_for_gating_strategy(user, project_id, flow_cytometry_id, gating_strategy_id)
    return result, status_code

# route to create a new gating element from a specific post request by the user based on parent id or not
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<flow_cytometry_id>/gating_strategies/<gating_strategy_id>/gating_elements', methods=['POST'])
@jwt_required()
def create_gating_element_views(project_id, flow_cytometry_id, gating_strategy_id):
    user = get_jwt_identity()
    data = request.get_json()
    result, status_code = gv.create_gating_element_views_v2(user, project_id, flow_cytometry_id, gating_strategy_id, data)
    return result, status_code


# route to remove a gating element
@bp.route('/api/v1/project/<project_id>/flow_cytometry/<flow_cytometry_id>/gating_strategies/<gating_strategy_id>/gating_elements/<gating_element_id>', methods = ["DELETE"])
@jwt_required()
def delete_gating_element_views(project_id, flow_cytometry_id, gating_strategy_id, gating_element_id):
    user = get_jwt_identity()
    data = request.get_json()
    # get the logic of delete gating element using the views file
    pass