services:
  metabolomics_service:
    build: .
    container_name: metabolomics_service
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - METABOLOMICS_ENV=${METABOLOMICS_ENV}
      - MONGO_URI_METABOLOMICS=${MONGO_URI_METABOLOMICS}
      - FLASK_RUN_METABOLOMICS_DEV_PORT=${FLASK_RUN_METABO_DEV_PORT}
      - FLASK_RUN_METABOLOMICS_PROD_PORT=${FLASK_RUN_METABO_PROD_PORT}
      - THERMO_RAW_FILE_PARSER_PATH=/tools/ThermoRawFileParser.exe
    volumes:
      - ./logs:/metabolomics_microservice/logs
      - ${DB_DIR}:${DB_DIR}
    networks: 
      - omnis_network
networks:
  omnis_network:
    external: true
    name: omnis_network