import pyopenms
import os
import subprocess
from dotenv import load_dotenv

load_dotenv()


# set up the percolator node
def run_percolator(input_pin_file, output_prefix):
    """
    Run Percolator from the command line on the given PIN file.
    
    Parameters:
    - input_pin_file (str): Path to the Percolator input (.pin) file.
    - output_prefix (str): Prefix for output files generated by Percolator.
    """
    percolator_command = [
        "percolator",
        "--trainFDR", "0.01",
        "--testFDR", "0.01",
        "--results-psms", f"{output_prefix}_psms.pin",
        input_pin_file
    ]
    
    print(f"Running Percolator: {' '.join(percolator_command)}")
    subprocess.run(percolator_command, check=True)
    print("Percolator processing complete.")


if __name__ == "__main__":
    # Example usage
    input_pin_file = os.path.join("/media/datastorage/it_cast/omnis_microservice_db/test_db", "20250228_04_01.pin")
    output_prefix = os.path.join("/media/datastorage/it_cast/omnis_microservice_db/test_db/", "percolator_results_20250228_04_01")
    
    run_percolator(input_pin_file, output_prefix)