
services:
  web:
    build:
      context: .
      args:
        OPENMS_DEB_URL: ${OPENMS_DEB_URL}  # Passa la variabile da .env al Dockerfile
    container_name: pipeline_microservice
    command: python run.py
    ports:
      - "5002:5002"
    environment:
      - PIPELINE_ENV=${PIPELINE_ENV}
      - MONGO_URI_AUTH=${MONGO_URI_AUTH}
      - MONGO_URI_METABOLOMICS=${MONGO_URI_METABOLOMICS}
      - MONGO_URI_FLOW_CYTOMETRY=${MONGO_URI_FLOW_CYTOMETRY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/pipeline_microservice
      - ./logs:/pipeline_microservice/logs
      - ${DB_DIR}:${DB_DIR}
    depends_on:
      - redis
    networks:
      - pipeline_network
      - omnis_network

  celery:
    build:
      context: .
      args:
        OPENMS_DEB_URL: ${OPENMS_DEB_URL}  # Stesso per celery
    container_name: pipeline_celery
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - MONGO_URI_FLOW_CYTOMETRY=${MONGO_URI_FLOW_CYTOMETRY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/pipeline_microservice
      - ./logs:/pipeline_microservice/logs
      - ${DB_DIR}:${DB_DIR}
    depends_on:
      - redis
    networks:
      - pipeline_network
      - omnis_network

  redis:
    image: redis:alpine
    container_name: pipeline_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pipeline_network

networks:
  pipeline_network:
    driver: bridge
  omnis_network:
    external: true
    name: omnis_network

volumes:
  redis_data:


